apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-scaling-load-tests-master
  namespace: demo
  labels:
    app: django-scaling-load-tests-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-scaling-load-tests-master
  template:
    metadata:
      labels:
        app: django-scaling-load-tests-master
    spec:
      containers:
        - name: django-scaling-load-tests
          image: django-scaling-load-tests:dev
          env:
            - name: "API_URL"
              value: "http://django-scaling:8000"
          command: [ "locust" ]
          args: [ "-f", "test_sample.py", "--master", "--web-port", "8000" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-scaling-load-tests-slave
  namespace: demo
  labels:
    app: django-scaling-load-tests-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-scaling-load-tests-slave
  template:
    metadata:
      labels:
        app: django-scaling-load-tests-slave
    spec:
      containers:
        - name: django-scaling-load-tests
          image: django-scaling-load-tests:dev
          env:
            - name: "API_URL"
              value: "http://django-scaling:8000"

          command: [ "locust" ]
          args: [ "-f", "test_sample.py", "--worker", "--master-host", "django-scaling-load-tests-master-api" ]

---
kind: Service
apiVersion: v1
metadata:
  name: django-scaling-load-tests-master-web
  namespace: demo
spec:
  type: NodePort
  selector:
    app: django-scaling-load-tests-master
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
      nodePort: 32001

---
apiVersion: v1
kind: Service
metadata:
  name: django-scaling-load-tests-master-api
  namespace: demo
spec:
  selector:
    app: django-scaling-load-tests-master
  ports:
    - protocol: TCP
      port: 5557
      targetPort: 5557